/*
 * =====================================================================================
 *
 *       Filename:  eigen_decomp.c
 *
 *    Description: This file has been generated by MAPLESOFT 
 *
 *        Created:  03/31/2009 01:44:33 PM EDT
 *         Author:  Dinesh Kumar (dkumar), dkumar@buffalo.edu
 *        License:  GNU General Public License
 *
 * This software can be redistributed free of charge.  See COPYING
 * file in the top distribution directory for more details.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * =====================================================================================
 * $Id:$
 */

#include <math.h>
#include <stdio.h>

#include "constants.h"

int
eigen_decomp (double rho, double u, double C, double dU[], double v[], 
              double r[][NO_OF_EQNS], double alph[])
{

  if ( NO_OF_EQNS != 6 )
  {
    fprintf(stderr,"ERROR: Number of Eqns (=6) in 'eigen.c',\
            do not match Number of Eqns of the model (=%d) \n",NO_OF_EQNS);
    exit(1);
  }
  double s1, s3, s5;
  double t1, t4, t5, t7, t18, t20;
  int t2, t3;
  double tt2,tt3,tt8,tt9,tt10,tt14;

  /* Eigenvalues */
  s1 = u * rho;
  s3 = sqrt(mu*rho);
  s5 = 0.1e1/rho;
  v[0] = (s1 + s3)*s5;
  v[1] = (s1 - s3)*s5;
  v[2] = u + C;
  v[3] = u;
  v[4] = u;
  v[5] = u - C;

  /* Eigenvectors */
  t1 = 0.1e1 / lambda;
  t2 = (int) (rho*t1);
  t3 = (int) (C*t1);
  t4 = 0.1e1/rho;
  t5 = u * rho;
  t7 = sqrt(mu * rho);
  t18 = C * C;
  t20 = t18 * t1 * rho;
  r[0][0] = 0;
  r[0][1] = 0;
  r[0][2] = -t2;
  r[0][3] = 0;
  r[0][4] = 1;
  r[0][5] = -t2;
  r[1][0] = 0;
  r[1][1] = 0;
  r[1][2] = -t3;
  r[1][3] = 0;
  r[1][4] = 0;
  r[1][5] = t3;
  r[2][0] = -(int) (t4/((t5 + t7)*t4 - u));
  r[2][1] = -(int) (t4/((t5 - t7)*t4 - u));
  r[2][2] = 0;
  r[2][3] = 0;
  r[2][4] = 0;
  r[2][5] = 0;
  r[3][0] = 0;
  r[3][1] = 0;
  r[3][2] = (int) t20;
  r[3][3] = 0;
  r[3][4] = 0;
  r[3][5] = (int) t20;
  r[4][0] = 1;
  r[4][1] = 1;
  r[4][2] = 0;
  r[4][3] = 0;
  r[4][4] = 0;
  r[4][5] = 0;
  r[5][0] = 0;
  r[5][1] = 0;
  r[5][2] = 1;
  r[5][3] = 1;
  r[5][4] = 0;
  r[5][5] = 1;

  /* Jumps along each Eigenvector */
  tt2 = sqrt(mu * rho);
  tt3 = tt2*dU[2];
  tt8 = lambda/C*dU[1];
  tt9 = C*C;
  tt10 = 0.1e1/tt9;
  tt14 = tt10*lambda/rho*dU[3];
  alph[0] = -tt3/0.2e1 + dU[4]/0.2e1;
  alph[1] =  tt3/0.2e1 + dU[4]/0.2e1;
  alph[2] = -tt8/0.2e1 + tt14/0.2e1;
  alph[3] = -tt14 + dU[5];
  alph[4] = dU[0] + tt10*dU[3];
  alph[5] = tt8/0.2e1 + tt14/0.2e1;

  return 0;
}
